import './scripts/local-storage'
import './scripts/transpose'
import './scripts/quantity'
import './scripts/modals'
import './scripts/minutes-seconds'
import './scripts/inputs'
import './scripts/theme'
import './scripts/piano'
import './scripts/background'
import './scripts/stopwatch'
import './scripts/countdown'
import './scripts/level-status'

import { Game } from './scripts/game'
new Game()
